apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobranca-email
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cobranca-email
  template:
    metadata:
      labels:
        app: cobranca-email
    spec:
      containers:
        - name: cobranca-email
          image: cobranca-email:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: cobranca-email-balancer
spec:
  selector:
    app: cobranca-email
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
